language: python

python:
- '3.6'

install:
- pip install -U -r ./.travis_pip_reqs.txt
- pip install -e .[reports]

script:
- pytest --cov
- python3 -m flake8 --exclude=build,doc,example,tmp --extend-ignore=F403,F405

after_success:
- codecov

deploy:
  provider: pypi
  username: yannik.schaelte
  password:
    secure: ewDnxKZIfntva4OURTnNGyCRcUQPvmj0RC9B54YoXgPtiTLirW3CyqfFhzUpNG8JWgK/2fiZhnNQjncDlreynhPre7CZPL/3Dp7oLBsCcFyzcu7gGCBSiCO9EbOG64VU3C7O4MVaxlas1mi3RegZm4SGRoOtg8uHhYbToz6FIBKYZ3uLkHlxrBQVCi669bDQrBb1M5K6AAf3b9cYlIW9rS7AeU0PZ4fuPU4SK++7Auhji6fhtOfAvKw9JwGxMKYL88hAOiEF7p9IyMl/tzRF8woP64spLjXC/5jmS6H2yaZmXT5XFEugRtCbWMo+l3cbG2LLtYkHt0yCQXJaxvFm+xOrbMt/5+8ynQ8AHzpjXHn1tWyQxC3GCFucRG0wY+6c4w7O1fS3DEikp/1ttj/wX88Nc25wuxIVb9dlMvGf6f6Mdy5wwfxuvuluaL9mDLR8Xmc17HArQqg1V6DGF+btkwQCPa/ZoU3WVItT52lEWDlO+2+8uj1O8yUUSHiAnCTNNreGUFP8x/sgduFMG3syo7wG5OX3l1HMPeLoWEBtc/I0AP7thmH0Rfj7EuyyQ+uJLJI1ugX+AOgGKQUOz5ikrggfKqHdTklaGVNNdoN67v8kNzrMFshdFWVm+SejczUgWbFQ4cOMhCW98RqN3lb6yvoO2i8lIhKY0KIfoYCrYN0=
  on:
    branch: master
    tags: true
