# MEASUREMENTS

OBSERVABLE_ID = 'observableId'
PREEQUILIBRATION_CONDITION_ID = 'preequilibrationConditionId'
SIMULATION_CONDITION_ID = 'simulationConditionId'
MEASUREMENT = 'measurement'
TIME = 'time'
OBSERVABLE_PARAMETERS = 'observableParameters'
OBSERVABLE_TRANSFORMATION = 'observableTransformation'
NOISE_DISTRIBUTION = 'noiseDistribution'
NOISE_PARAMETERS = 'noiseParameters'
DATASET_ID = 'datasetId'
REPLICATE_ID = 'replicateId'

MEASUREMENT_DF_REQ_COLS = [
    OBSERVABLE_ID, PREEQUILIBRATION_CONDITION_ID, SIMULATION_CONDITION_ID,
    MEASUREMENT, OBSERVABLE_PARAMETERS, NOISE_PARAMETERS,
    NOISE_DISTRIBUTION]

MEASUREMENT_DF_COLS = [
    *MEASUREMENT_DF_REQ_COLS, DATASET_ID, REPLICATE_ID]


# PARAMETERS

PARAMETER_ID = 'parameterId'
PARAMETER_NAME = 'parameterName'
PARAMETER_SCALE = 'parameterScale'
LOWER_BOUND = 'lowerBound'
UPPER_BOUND = 'upperBound'
NOMINAL_VALUE = 'nominalValue'
ESTIMATE = 'estimate'
PRIOR_TYPE = 'priorType'
PRIOR_PARAMETERS = 'priorParameters'
OBJECTIVE_PRIOR_TYPE = 'objectivePriorType'
OBJECTIVE_PRIOR_PARAMETERS = 'objectivePriorParameters'

PARAMETER_DF_REQ_COLS = [
    PARAMETER_ID, PARAMETER_SCALE, LOWER_BOUND, UPPER_BOUND, NOMINAL_VALUE,
    ESTIMATE]

PARAMETER_DF_COLS = [
    PARAMETER_ID, PARAMETER_NAME, PARAMETER_DF_REQ_COLS[1:],
    PRIOR_TYPE, PRIOR_PARAMETERS,
    OBJECTIVE_PRIOR_TYPE, OBJECTIVE_PRIOR_PARAMETERS]


# CONDITIONS


# TRANSFORMATIONS

LIN = 'lin'
LOG = 'log'
LOG10 = 'log10'


# NOISE MODELS

UNIFORM = 'uniform'
NORMAL = 'normal'
LAPLACE = 'laplace'
